// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_SIGNAL: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_SIGNAL: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_SIGNAL: [Signal; 4] = [
  Signal::NONE,
  Signal::Message,
  Signal::Unknown,
  Signal::Timeout,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Signal(pub u8);
#[allow(non_upper_case_globals)]
impl Signal {
  pub const NONE: Self = Self(0);
  pub const Message: Self = Self(1);
  pub const Unknown: Self = Self(2);
  pub const Timeout: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Message,
    Self::Unknown,
    Self::Timeout,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Message => Some("Message"),
      Self::Unknown => Some("Unknown"),
      Self::Timeout => Some("Timeout"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Signal {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Signal {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Signal {
    type Output = Signal;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Signal {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Signal {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Signal {}
pub struct SignalUnionTableOffset {}

// struct Timestamp, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Timestamp(pub [u8; 8]);
impl Default for Timestamp { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for Timestamp {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Timestamp")
      .field("unix_ms", &self.unix_ms())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Timestamp {}
impl<'a> ::flatbuffers::Follow<'a> for Timestamp {
  type Inner = &'a Timestamp;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Timestamp>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Timestamp {
  type Inner = &'a Timestamp;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Timestamp>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Timestamp {
    type Output = Timestamp;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Timestamp as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> ::flatbuffers::Verifiable for Timestamp {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Timestamp {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    unix_ms: i64,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_unix_ms(unix_ms);
    s
  }

  pub fn unix_ms(&self) -> i64 {
    let mut mem = ::core::mem::MaybeUninit::<<i64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_unix_ms(&mut self, x: i64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct Snowflake, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Snowflake(pub [u8; 8]);
impl Default for Snowflake { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl ::core::fmt::Debug for Snowflake {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Snowflake")
      .field("uid", &self.uid())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Snowflake {}
impl<'a> ::flatbuffers::Follow<'a> for Snowflake {
  type Inner = &'a Snowflake;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Snowflake>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Snowflake {
  type Inner = &'a Snowflake;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Snowflake>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Snowflake {
    type Output = Snowflake;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Snowflake as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> ::flatbuffers::Verifiable for Snowflake {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Snowflake {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    uid: u64,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_uid(uid);
    s
  }

  pub fn uid(&self) -> u64 {
    let mut mem = ::core::mem::MaybeUninit::<<u64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_uid(&mut self, x: u64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum UnknownOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Unknown<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Unknown<'a> {
  type Inner = Unknown<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Unknown<'a> {
  pub const VT_DATA: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Unknown { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UnknownArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Unknown<'bldr>> {
    let mut builder = UnknownBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    builder.finish()
  }


  #[inline]
  pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Unknown::VT_DATA, None)}
  }
}

impl ::flatbuffers::Verifiable for Unknown<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct UnknownArgs<'a> {
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for UnknownArgs<'a> {
  #[inline]
  fn default() -> Self {
    UnknownArgs {
      data: None,
    }
  }
}

pub struct UnknownBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnknownBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Unknown::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UnknownBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UnknownBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Unknown<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Unknown<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Unknown");
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Message<'a> {
  pub const VT_CHANNEL_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_GUILD_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.guild_id { builder.add_guild_id(x); }
    if let Some(x) = args.channel_id { builder.add_channel_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn channel_id(&self) -> Option<&'a Snowflake> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Snowflake>(Message::VT_CHANNEL_ID, None)}
  }
  #[inline]
  pub fn guild_id(&self) -> &'a Snowflake {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Snowflake>(Message::VT_GUILD_ID, None).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Message::VT_DATA, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Snowflake>("channel_id", Self::VT_CHANNEL_ID, false)?
     .visit_field::<Snowflake>("guild_id", Self::VT_GUILD_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs<'a> {
    pub channel_id: Option<&'a Snowflake>,
    pub guild_id: Option<&'a Snowflake>,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for MessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      channel_id: None,
      guild_id: None, // required field
      data: None, // required field
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_channel_id(&mut self, channel_id: &Snowflake) {
    self.fbb_.push_slot_always::<&Snowflake>(Message::VT_CHANNEL_ID, channel_id);
  }
  #[inline]
  pub fn add_guild_id(&mut self, guild_id: &Snowflake) {
    self.fbb_.push_slot_always::<&Snowflake>(Message::VT_GUILD_ID, guild_id);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Message::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Message::VT_GUILD_ID,"guild_id");
    self.fbb_.required(o, Message::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("channel_id", &self.channel_id());
      ds.field("guild_id", &self.guild_id());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum TimeoutOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Timeout<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Timeout<'a> {
  type Inner = Timeout<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Timeout<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Timeout { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TimeoutArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Timeout<'bldr>> {
    let mut builder = TimeoutBuilder::new(_fbb);
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> &'a Snowflake {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Snowflake>(Timeout::VT_ID, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Timeout<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Snowflake>("id", Self::VT_ID, true)?
     .finish();
    Ok(())
  }
}
pub struct TimeoutArgs<'a> {
    pub id: Option<&'a Snowflake>,
}
impl<'a> Default for TimeoutArgs<'a> {
  #[inline]
  fn default() -> Self {
    TimeoutArgs {
      id: None, // required field
    }
  }
}

pub struct TimeoutBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TimeoutBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: &Snowflake) {
    self.fbb_.push_slot_always::<&Snowflake>(Timeout::VT_ID, id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TimeoutBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TimeoutBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Timeout<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Timeout::VT_ID,"id");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Timeout<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Timeout");
      ds.field("id", &self.id());
      ds.finish()
  }
}
pub enum PacketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Packet<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Packet<'a> {
  type Inner = Packet<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Packet<'a> {
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 4;
  pub const VT_ORIGIN_NODE: ::flatbuffers::VOffsetT = 6;
  pub const VT_SIGNAL_TYPE: ::flatbuffers::VOffsetT = 8;
  pub const VT_SIGNAL: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Packet { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PacketArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Packet<'bldr>> {
    let mut builder = PacketBuilder::new(_fbb);
    if let Some(x) = args.signal { builder.add_signal(x); }
    if let Some(x) = args.origin_node { builder.add_origin_node(x); }
    if let Some(x) = args.timestamp { builder.add_timestamp(x); }
    builder.add_signal_type(args.signal_type);
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> &'a Timestamp {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timestamp>(Packet::VT_TIMESTAMP, None).unwrap()}
  }
  #[inline]
  pub fn origin_node(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Packet::VT_ORIGIN_NODE, None).unwrap()}
  }
  #[inline]
  pub fn signal_type(&self) -> Signal {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Signal>(Packet::VT_SIGNAL_TYPE, Some(Signal::NONE)).unwrap()}
  }
  #[inline]
  pub fn signal(&self) -> ::flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Packet::VT_SIGNAL, None).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn signal_as_message(&self) -> Option<Message<'a>> {
    if self.signal_type() == Signal::Message {
      let u = self.signal();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Message::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn signal_as_unknown(&self) -> Option<Unknown<'a>> {
    if self.signal_type() == Signal::Unknown {
      let u = self.signal();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Unknown::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn signal_as_timeout(&self) -> Option<Timeout<'a>> {
    if self.signal_type() == Signal::Timeout {
      let u = self.signal();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Timeout::init_from_table(u) })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Packet<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Timestamp>("timestamp", Self::VT_TIMESTAMP, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("origin_node", Self::VT_ORIGIN_NODE, true)?
     .visit_union::<Signal, _>("signal_type", Self::VT_SIGNAL_TYPE, "signal", Self::VT_SIGNAL, true, |key, v, pos| {
        match key {
          Signal::Message => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Message>>("Signal::Message", pos),
          Signal::Unknown => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Unknown>>("Signal::Unknown", pos),
          Signal::Timeout => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Timeout>>("Signal::Timeout", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct PacketArgs<'a> {
    pub timestamp: Option<&'a Timestamp>,
    pub origin_node: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub signal_type: Signal,
    pub signal: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for PacketArgs<'a> {
  #[inline]
  fn default() -> Self {
    PacketArgs {
      timestamp: None, // required field
      origin_node: None, // required field
      signal_type: Signal::NONE,
      signal: None, // required field
    }
  }
}

pub struct PacketBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PacketBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: &Timestamp) {
    self.fbb_.push_slot_always::<&Timestamp>(Packet::VT_TIMESTAMP, timestamp);
  }
  #[inline]
  pub fn add_origin_node(&mut self, origin_node: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Packet::VT_ORIGIN_NODE, origin_node);
  }
  #[inline]
  pub fn add_signal_type(&mut self, signal_type: Signal) {
    self.fbb_.push_slot::<Signal>(Packet::VT_SIGNAL_TYPE, signal_type, Signal::NONE);
  }
  #[inline]
  pub fn add_signal(&mut self, signal: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Packet::VT_SIGNAL, signal);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PacketBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PacketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Packet<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Packet::VT_TIMESTAMP,"timestamp");
    self.fbb_.required(o, Packet::VT_ORIGIN_NODE,"origin_node");
    self.fbb_.required(o, Packet::VT_SIGNAL,"signal");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Packet<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Packet");
      ds.field("timestamp", &self.timestamp());
      ds.field("origin_node", &self.origin_node());
      ds.field("signal_type", &self.signal_type());
      match self.signal_type() {
        Signal::Message => {
          if let Some(x) = self.signal_as_message() {
            ds.field("signal", &x)
          } else {
            ds.field("signal", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Signal::Unknown => {
          if let Some(x) = self.signal_as_unknown() {
            ds.field("signal", &x)
          } else {
            ds.field("signal", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Signal::Timeout => {
          if let Some(x) = self.signal_as_timeout() {
            ds.field("signal", &x)
          } else {
            ds.field("signal", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("signal", &x)
        },
      };
      ds.finish()
  }
}
